// import { useState } from 'react/cjs/react.production.min'
import Head from 'next/head'
import Link from 'next/link';
import React from 'react';


import styles from '../styles/Home.module.css'


export default function Home() {

const [text, setText] = React.useState()
console.log(setText.value)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
    
        <Link href='form'>
          <a>teste do form</a>
        </Link>
        <Link href='formi1'>
          <a>teste do form1</a>
        </Link>
        <Link href="form2">
          <a>Form 2 com Input radio</a>
        </Link>
        <Link href="testeISR">
          <a>Teste ISR</a>
        </Link>
        <Link href="toggle">
          <a>Teste toggle</a>
        </Link>
        <Link href="testeReact">
          <a>Teste React</a>
        </Link>
        <Link href="fonteIcon">
          <a>Font Awesome</a>
        </Link>
        
      </main>
    </div>
  )
}
