// import { useState } from 'react/cjs/react.production.min'
import Head from 'next/head'
import Link from 'next/link';
import React from 'react';





export default function Home() {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
    
        <Link href='form'>
          <a>teste do form</a>
        </Link>
        <Link href='formi1'>
          <a>teste do form1</a>
        </Link>
        <Link href="form2">
          <a>Form 2 com Input radio</a>
        </Link>
        <Link href="testeISR">
          <a>Teste ISR</a>
        </Link>
        <Link href="toggle">
          <a>Teste toggle</a>
        </Link>
        <Link href="testeReact">
          <a>Teste React</a>
        </Link>
        <Link href="fonteIcon">
          <a>Font Awesome</a>
        </Link>
        <Link href="money">
          <a>tamo a falar de money</a>
        </Link>
        
      </main>
    </div>
  )
}
